export const reportCatalog = {
  routeIntelligence: {
    slug: "route-intelligence",
    name: "Route Intelligence",
    question: "Do you know the route, distance, elevation, and terrain for every routed activity?",
    summary: "Map, terrain, elevation, waypoints and relevant access information in one route record.",
    href: "/for-schools/route-intelligence",
    image: "/showcase/pages/02-3-itoshima-route/1.png",
    imageAlt: "ETI360 Route Intelligence map for the Big Itoshima cycling route",
  },
  locationTimeline: {
    slug: "location-timeline",
    name: "Calendar + Timeline",
    question: "Do you know the scheduled location of every trip group, on every trip?",
    summary: "One structured itinerary presented as a detailed calendar and a continuous trip timeline.",
    href: "/for-schools/location-timeline",
    image: "/codex/MarketingCampaign/location-timeline.png",
    imageAlt: "ETI360 Location Timeline across five days",
  },
  weatherBrief: {
    slug: "weather-brief",
    name: "Weather Brief",
    question: "Have historical seasonal conditions been reviewed against each location and date in the itinerary?",
    summary: "Historical climate context connected to preparation and adjustable risk information.",
    href: "/for-schools/weather-brief",
    image: "/showcase/pages/01-1-weather-brief-sydney/1.png",
    imageAlt: "ETI360 Weather Brief for Sydney in March",
  },
  medicalAccess: {
    slug: "medical-access",
    name: "Medical Access",
    question: "Can your team see the medical facilities and travel times connected to each planned location?",
    summary: "Verified facility details and estimated access information connected to the actual itinerary.",
    href: "/for-schools/medical-access",
    image: "/Claude/Questions/assets/medical-access.png",
    imageAlt: "ETI360 verified medical facility profiles",
  },
  studentJourney: {
    slug: "student-journey",
    name: "Student Journey Guide",
    question: "Is the educational purpose of each trip connected to its daily activities?",
    summary: "The learning purpose, the named activities and the shape of each day in one student-facing guide.",
    href: "/for-schools/student-journey",
    image: "/Claude/Questions/assets/student-journey-day.png",
    imageAlt: "ETI360 Student Journey Guide day page with map, activity cards and an hour-by-hour view of the day",
  },
  standardDocumentation: {
    slug: "standard-documentation",
    name: "Standard Trip Documentation",
    question: "Do all of your field trips use the same documentation format?",
    summary: "A consistent structure across different trips, generated from one trip-specific record.",
    href: "/for-schools/standard-documentation",
    image: "/Claude/Questions/assets/std-documentation.png",
    imageAlt: "Three ETI360 itinerary documents using one standard format",
  },
  dutyManager: {
    slug: "duty-manager",
    name: "Duty Manager Dashboard",
    question: "Can your duty manager see where every traveling group is scheduled to be across all active trips?",
    summary: "Trip context with calls, messages, check-ins and follow-up tracked in one operating view.",
    href: "/for-schools/duty-manager",
    image: "/Claude/Questions/assets/scheduled-group-locations.png",
    imageAlt: "ETI360 Duty Manager Dashboard with six current trips, the selected trip's scheduled location, and the next four hours across every trip",
  },
  incidentReporting: {
    slug: "incident-reporting",
    name: "Incident Reporting",
    question: "Can your duty team log an incident, track its status, and preserve the full record in one place?",
    summary: "Context, communications, actions, status and retained documentation in one record.",
    href: "/for-schools/incident-reporting",
    image: "/Claude/Questions/assets/incident-record.png",
    imageAlt: "ETI360 integrated incident record",
  },
} as const;

export const reportList = Object.values(reportCatalog);
